config/routes.rb
Rails.application.routes.draw do
  get 'api_request/new'
  post 'api_request/create'

  root 'api_request#new'

end

app/models/api_request.rb
class ApiRequest
  include ActiveModel::Model
 
  attr_accessor :uid, :pub0, :page
  validates :uid, :pub0, :page, presence: true
end

app/controllers/api_request_controller.rb
class ApiRequestController < ApplicationController
  def new
    @api_request = ApiRequest.new
  end

  def create
    @api_request = ApiRequest.new(api_request_params)

    respond_to do |format|
      if @api_request.valid?
        begin
          @offers = FyberApiWrapper.get_offers(api_request_params)
        rescue Exception => e
          @error_message = e.message
          format.html { render :error }
        else
          format.html
        end
      else
        format.html { render :new }
      end
    end
  end

  private
    def api_request_params
      params.require(:api_request).permit(:uid, :pub0, :page)
    end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/api_request_helper.rb
module ApiRequestHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/api_request/_offer.html.erb
<table>
  <tr><th>Link:</th><td><%= offer.link %></td></tr>
  <tr><th>Title:</th><td><%= offer.title %></td></tr>
  <tr><th>Offer ID:</th><td><%= offer.offer_id %></td></tr>
  <tr><th>Teaser:</th><td><%= offer.teaser %></td></tr>
  <tr><th>Required Actions:</th><td><%= offer.required_actions %></td></tr>
  <tr>
    <th rowspan="2">Thumbnail:</th>
    <td><span class="response_label">lowres:</span><%= offer.thumbnail.lowres %></td>
  </tr>
  <tr>
    <td><span class="response_label">hires:</span><%= offer.thumbnail.hires %></td>
  </tr>

  <% if offer.offer_types.size > 0 %>
    <tr>
      <th rowspan="<%= offer.offer_types.size %>">Offer Types:</th>
      <td>
        <span class="response_label">offer_type_id:</span><%= offer.offer_types[0].offer_type_id %>
        <span class="response_label">readable:</span><%= offer.offer_types[0].readable %>
      </td>
    </tr>
    <% offer.offer_types[1..-1].each do |offer_type| %>
      <tr>
        <td>
          <span class="response_label">offer_type_id:</span><%= offer_type.offer_type_id %>
          <span class="response_label">readable:</span><%= offer_type.readable %>
        </td>
      </tr>
    <% end %>
  <% end %>

  <tr><th>Payout:</th><td><%= offer.payout %></td></tr>
  <tr>
    <th rowspan="2">Time to Payout:</th>
    <td><span class="response_label">amount:</span><%= offer.time_to_payout.amount %></td>
  </tr>
  <tr>
    <td><span class="response_label">readable:</span><%= offer.time_to_payout.readable %></td>
  </tr>
</table>

app/views/api_request/create.html.erb
<h1>API Response</h1>
<p><%= link_to "Go back", api_request_new_path %></p>
<h2>Response info</h2>
<p>
  <span class="response_label">Code:</span> <%= @offers.code %><br/>
  <span class="response_label">Message:</span> <%= @offers.message %><br/>
  <span class="response_label">Count:</span> <%= @offers.count %><br/>
  <span class="response_label">Pages:</span> <%= @offers.pages %>
</p>
<h2>Information</h2>
<p>
  <span class="response_label">app_name:</span> <%= @offers.information.app_name %><br/>
  <span class="response_label">appid:</span> <%= @offers.information.appid %><br/>
  <span class="response_label">virtual_currency:</span> <%= @offers.information.virtual_currency %><br/>
  <span class="response_label">country:</span> <%= @offers.information.country %><br/>
  <span class="response_label">language:</span> <%= @offers.information.language %><br/>
  <span class="response_label">support_url:</span> <%= @offers.information.support_url %>
</p>
<h2>Offers</h2>
<% @offers.each do |offer| %>
  <%= render 'offer', offer: offer %>
<% end %>
<p><%= link_to "Go back", api_request_new_path %></p>

app/views/api_request/error.html.erb
<p><%= @error_message %></p>
<p><%= link_to "Go back", api_request_new_path %></p>

app/views/api_request/new.html.erb
<h1>Offer request details</h1>
<p>Fill the requiered details</p>
<% @api_request.errors.full_messages.each do |m| %>
  <ul class="error_message">
    <li><%= m %>
  </ul>
<% end %>
<%= form_for @api_request, url: api_request_create_path do |f| %>
  <p>
    <%= f.label :uid %><br/>
    <%= f.text_field :uid %>
  </p>
  <p>
    <%= f.label :pub0 %><br/>
    <%= f.text_field :pub0 %>
  </p>
  <p>
    <%= f.label :page %><br/>
    <%= f.text_field :page %>
  </p>
  <%= f.submit "Create" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fyber</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>